export default {
    english: {
        title: 'Randomization Service',
        noPending: 'You have no pending requests!',
        code_1: 'IN QUEUE',
        code_2: 'IN PROGRESS',
        code_3: 'RESULTS SENT OVER EMAIL',
        code_4: 'THERE WAS A PROBLEM, PLEASE CHECK EMAIL.',
        loading: 'Loading...',
        networkTitle: 'Network Error',
        networkMessage: 'Check your internet connection',
        troubleTitle: 'What is this?',
        troubleText: 'This is our randomization service. Here you can customize whatever randomization you need. All you have to do is make a request, providing all the details/requirements needed. You can track the status of your request and once it is done a report (with the results) will be sent to your email.\n\n\nFor any issue go to:\nSettings > Support',
        troubleClose: 'Tap anywhere to close.',
        newRequest: 'New request',
    },
    portuguese: {
        title: 'Serviço de randomização',
        noPending: 'Você não tem pedidos pendentes!',
        code_1: 'AGUARDANDO',
        code_2: 'EM PROGRESSO',
        code_3: 'RESULTADOS ENVIADOS POR EMAIL',
        code_4: 'HOUVE UM PROBLEMA, ACESSE SEU EMAIL.',
        loading: 'Carregando...',
        networkTitle: 'Erro de conexão',
        networkMessage: 'Confira sua conexão com a internet.',
        troubleTitle: 'O que é isso?',
        troubleText: 'Esse é nosso serviço de randomização. Aqui você pode customizar seus sorteios. Tudo que você precisa fazer é criar um pedido, fornecendo todos os detalhes necessários. Você pode acompanhar o progresso do seu pedido e quando estiver pronto você receberá um relatório (com os resultados) em seu email.\n\n\nPara qualquer problema:\nConfiguraçōes > Suporte',
        troubleClose: 'Clique para fechar.',
        newRequest: 'Novo pedido',
    },
    spanish: {
        title: 'Servicio de aleatorización',
        noPending: 'No tiene solicitudes pendientes.',
        code_1: 'ESPERANDO',
        code_2: 'EN CURSO',
        code_3: 'RESULTADOS DEL EMAIL',
        code_4: 'HUBO UN PROBLEMA, REVISA TU EMAIL.',
        loading: 'Cargando...',
        networkTitle: 'Error de conexión',
        networkMessage: 'Revise su conexión a Internet.',
        troubleTitle: '¿Qué es esto?',
        troubleText: 'Este es nuestro servicio de aleatorización. Aquí puedes personalizar tus aleatorizaciones. Todo lo que necesitas hacer es crear una solicitud, proporcionando la información necesaria. Puede rastrear su pedido y cuando esté listo se le enviará un informe a su email.\n\n\nPara cualquier asunto:\nConfiguración > Soporte',
        troubleClose: 'haga clic para cerrar.',
        newRequest: 'Nueva solicitud',
    },
    chinese: {
        title: '随机化服务',
        noPending: '您没有待处理的请求!',
        code_1: '排队',
        code_2: '进行中',
        code_3: '邮件发送结果',
        code_4: '有问题，请查看邮件',
        loading: '加载',
        networkTitle: '网络错误',
        networkMessage: '检查您的网络连接',
        troubleTitle: '这是什么？',
        troubleText: '这就是我们的随机化服务。在这里，您可以定制任何您需要的随机化服务。您只需提出请求，提供所有的细节/要求。您可以跟踪您的请求的状态，一旦完成后，我们会将报告（包括结果）发送到您的邮箱。.\n\n\n对于任何问题，请到:\设置 > 支持',
        troubleClose: '点击关闭',
        newRequest: '新要求',
    },
    german: {
        title: 'Randomisierungsdienst',
        noPending: 'Sie haben keine anhängigen Anträge!',
        code_1: 'In der Warteschlange',
        code_2: 'In Bearbeitung',
        code_3: 'Ergebnisse per E-Mail verschickt',
        code_4: 'Es gab ein Problem, bitte prüfen Sie die E-Mail',
        loading: 'Laden...',
        networkTitle: 'Netzwerk-Fehler',
        networkMessage: 'Überprüfen Sie Ihre Internetverbindung',
        troubleTitle: 'Was ist das?',
        troubleText: 'Dies ist unser Randomisierungsdienst. Hier können Sie die von Ihnen benötigte Randomisierung anpassen. Alles, was Sie tun müssen, ist eine Anfrage zu stellen, die alle benötigten Details/Anforderungen enthält. Sie können den Status Ihrer Anfrage verfolgen, und sobald diese abgeschlossen ist, wird Ihnen ein Bericht (mit den Ergebnissen) per E-Mail zugesandt.\n\n\nFür jede Ausgabe gehen Sie zu:\nEinstellungen > Support',
        troubleClose: 'Klicken Sie zum SchließenTap anywhere to close.',
        newRequest: 'Neue Anfrage',
    },
}