export default {
    english: {
        title: 'Lists & Orders',
        placeholder: 'Enter name',
        remove: 'Long press any name to remove it.',
        pickName: 'Pick name',
        randomOrder: 'Shuffle order',
        close: 'Tap anywhere to close',
    },
    portuguese: {
        title: 'Listas e Ordens',
        placeholder: 'Insira um nome',
        remove: 'Segure em um nome para removê-lo.',
        pickName: 'Sortear nome',
        randomOrder: 'Embaralhar',
        close: 'Clique para fechar',
    },
    spanish: {
        title: 'Listas y Órdenes',
        placeholder: 'Agregar un nombre',
        remove: 'Mantenga un nombre para eliminarlo.',
        pickName: 'Nombre al azar',
        randomOrder: 'Barajar',
        close: 'Haga clic para cerrar.',
    },
    chinese: {
        title: '清单和订单',
        placeholder: '输入名称',
        remove: '点住以删除',
        pickName: '选择一个名字',
        randomOrder: '洗牌',
        close: '点击关闭',
    },
    german: {
        title: 'Listen und Bestellungen',
        placeholder: 'Namen eingeben',
        remove: 'Zum Entfernen berühren und halten.',
        pickName: 'Wähle den Namen',
        randomOrder: 'Mischen',
        close: 'Klicken Sie zum Schließen',
    },
}