export default {
    english: {
        title: 'Settings',
        language: 'Language',
        about: 'About',
        version : 'Version ',
        modalText: 'Developer:\nThiago Guerino Amaral.\n\nCore Contributors:\nRodrigo Rodrigues Amaral, Maria Ilma de Souza Cortes and the Pontifical Catholic University of Minas Gerais.\n\nFor any issue contact the developer on:\n\nthiagoguerinoamaral@gmail.com',
        modalClose: 'Tap anywhere to close.',
        support: 'Support',
    },
    portuguese: {
        title: 'Configurações',
        language: 'Idioma',
        about: 'Sobre',
        version : 'Versão ',
        modalText: 'Desenvolvedor:\nThiago Guerino Amaral.\n\nContribuidores fundamentais:\nRodrigo Rodrigues Amaral, Maria Ilma de Souza Cortes e PUC-Minas.\n\nSinta-se à vontade para contactar o desenvolvedor por qualquer situação:\n\nthiagoguerinoamaral@gmail.com',
        modalClose: 'Clique para fechar.',
        support: 'Suporte',
    },
    spanish: {
        title: 'Configuración',
        language: 'Idioma',
        about: 'Sobre',
        version : 'Versión ',
        modalText: 'Desarrollador:\nThiago Guerino Amaral.\n\nColaboradores clave:\nRodrigo Rodrigues Amaral, Maria Ilma de Souza Cortes e Pontificia Universidad Católica de Minas Gerais.\n\nPóngase en contacto con el desarrollador en:\n\nthiagoguerinoamaral@gmail.com',
        modalClose: 'Toca para cerrar.',
        support: 'Soporte',
    },
    chinese: {
        title: '设定',
        language: '语言',
        about: '关于',
        version : '版 ',
        modalText: '开发商：\nThiago Guerino Amaral\n\n杰出贡献者：\nRodrigo Rodrigues Amaral, Maria Ilma de Souza Cortes, 米纳斯吉拉斯天主教大学。\n\n随时通过以下方式与开发者联系：\n\nthiagoguerinoamaral@gmail.com',
        modalClose: '点按任意位置以关闭。',
        support: '支援',
    },
    german: {
        title: 'Einstellungen',
        language: 'Sprache',
        about: 'Über',
        version : 'Version ',
        modalText: 'Entwickler:\nThiago Guerino Amaral.\n\nHauptbeitragszahler:\nRodrigo Rodrigues Amaral, Maria Ilma de Souza Cortes und die Päpstliche Katholische Universität Minas Gerais.\n\nKontaktieren Sie den Entwickler unter:\n\nthiagoguerinoamaral@gmail.com',
        modalClose: 'Klicken Sie zum Schließen.',
        support: 'Support',
    },
}