export default {
    english: {
        title: 'Random Number Generator',
        placeholder: 'Enter here',
        from: 'From',
        to: 'To',
        howMany: 'How many?',
        repetition: 'Repetition',
        generate: 'GENERATE',
    },
    portuguese: {
        title: 'Gerador de Números Aleatórios',
        placeholder: 'Digite aqui',
        from: 'Mínimo',
        to: 'Máximo',
        howMany: 'Quantos?',
        repetition: 'Repetição',
        generate: 'GERAR',
    },
    spanish: {
        title: 'Generador de números aleatorios',
        placeholder: 'Escriba aquí',
        from: 'Mínimo',
        to: 'Máximo',
        howMany: '¿Cuántos?',
        repetition: 'Repetición',
        generate: 'GENERAR',
    },
    chinese: {
        title: '随机数发生器',
        placeholder: '在这里输入',
        from: '最低',
        to: '最大值',
        howMany: '多少？',
        repetition: '重复',
        generate: '生成',
    },
    german: {
        title: 'Zufallszahlengenerator',
        placeholder: 'Hier eintreten',
        from: 'Minimum',
        to: 'Maximum',
        howMany: 'Wie viele?',
        repetition: 'Wiederholung',
        generate: 'ERZEUGEN',
    },
}